imports:
    - { resource: ../../../../../app/config/parameters.yml }

services:
    wio.edk.repo.route:
        class:     WIO\EdkBundle\Repository\EdkRouteRepository
        arguments: ["@database_connection", "@cantiga.transaction", "@event_dispatcher", "@cantiga.time", "@cantiga.files"]
    wio.edk.repo.export:
        class:     WIO\EdkBundle\Repository\EdkExportRepository
        arguments: ["@database_connection"]
    wio.edk.repo.registration:
        class:     WIO\EdkBundle\Repository\EdkRegistrationSettingsRepository
        arguments: ["@database_connection", "@cantiga.transaction", "@cantiga.time"]
    wio.edk.repo.message:
        class:     WIO\EdkBundle\Repository\EdkMessageRepository
        arguments: ["@database_connection", "@cantiga.transaction", "@cantiga.time"]
    wio.edk.repo.published_data:
        class:     WIO\EdkBundle\Repository\EdkPublishedDataRepository
        arguments: ["@database_connection", "@cantiga.transaction"]
    wio.edk.repo.participant:
        class:     WIO\EdkBundle\Repository\EdkParticipantRepository
        arguments: ["@database_connection", "@cantiga.transaction", "@event_dispatcher", "@cantiga.time"]
    wio.edk.extension.area_information_map:
        class:     WIO\EdkBundle\Extension\AreaInformationMapExtension
        arguments: ["@templating"]
        tags:
            - { name: cantiga.extension, point: core.page.area.info, module: edk }
    wio.edk.extension.area_routes:
        class:     WIO\EdkBundle\Extension\AreaRouteExtension
        arguments: ["@wio.edk.repo.route", "@templating"]
        tags:
            - { name: cantiga.extension, point: core.page.area.info, module: edk }
    wio.edk.form.area_request:
        class:     WIO\EdkBundle\CustomForm\AreaRequestModel
        arguments: ["@translator"]
        tags:
            - { name: cantiga.extension, point: core.form.area-request, module: edk, description: "EDK area request form" }
    wio.edk.form.area:
        class:     WIO\EdkBundle\CustomForm\AreaModel
        arguments: ["@translator"]
        tags:
            - { name: cantiga.extension, point: core.form.area, module: edk, description: "EDK area form" }
    wio.edk.mailing_listener:
        class: WIO\EdkBundle\EventListener\MailingListener
        arguments: ["@cantiga.mail.sender"]
        tags:
            - { name: kernel.event_listener, event: edk.registration.completed, method: onRegistrationCompleted }
    wio.edk.model_listener:
        class: WIO\EdkBundle\EventListener\ModelListener
        arguments: ["@event_dispatcher"]
        tags:
            - { name: kernel.event_listener, event: cantiga.project.created, method: onProjectCreated }
            - { name: kernel.event_listener, event: cantiga.area.updated, method: onAreaUpdated }
    wio.edk.export_listener:
         class: WIO\EdkBundle\EventListener\ExportListener
         arguments: ["@wio.edk.repo.export"]
         tags:
            - { name: kernel.event_listener, event: cantiga.export.ongoing, method: onProjectExported }
    wio.edk.workspace_listener:
        class: WIO\EdkBundle\EventListener\WorkspaceListener
        arguments: ["@security.authorization_checker"]
        tags:
            - { name: kernel.event_listener, event: cantiga.workspace.project, method: onProjectWorkspace }
            - { name: kernel.event_listener, event: cantiga.workspace.group, method: onGroupWorkspace }
            - { name: kernel.event_listener, event: cantiga.workspace.area, method: onAreaWorkspace }
            - { name: kernel.event_listener, event: cantiga.ui.ctxmenu.project.area, method: onProjectAreaInfo }
    wio.edk.dashboard.recent_comments:
        class:     WIO\EdkBundle\Extension\DashboardChatExtension
        arguments: ["@wio.edk.repo.route", "@templating", "@cantiga.user.membership.storage"]
        tags:
            - { name: cantiga.extension, point: core.dashboard.area.central, module: edk }
            - { name: cantiga.extension, point: core.dashboard.group.central, module: edk }
    wio.edk.dashboard.recent_routes:
        class:     WIO\EdkBundle\Extension\DashboardRouteExtension
        arguments: ["@wio.edk.repo.route", "@templating", "@cantiga.user.membership.storage"]
        tags:
            - { name: cantiga.extension, point: core.dashboard.area.central, module: edk }
            - { name: cantiga.extension, point: core.dashboard.group.central, module: edk }
    wio.edk.dashboard.route_summary:
        class: WIO\EdkBundle\Extension\DashboardRouteSummaryExtension
        arguments: ["@wio.edk.repo.route", "@wio.edk.repo.registration", "@templating", "@cantiga.user.membership.storage"]
        tags:
            - { name: cantiga.extension, point: core.dashboard.project.top, module: edk }
            - { name: cantiga.extension, point: core.dashboard.group.top, module: edk }
            - { name: cantiga.extension, point: core.dashboard.area.top, module: edk }
    wio.edk.button.area_contact_grabber:
         class: WIO\EdkBundle\Extension\AreaContactGrabberButton
         arguments: ["@database_connection"]
         tags:
            - { name: cantiga.extension, point: core.magic-button, module: edk, description: "Get contacts to area leaders" }
    wio.edk.stats.route_length:
        class: WIO\EdkBundle\Statistics\RouteLengthHistogram
        arguments: ["@database_connection"]
        tags:
            - { name: cantiga.extension, point: edk.stats.route, module: edk }
    wio.edk.stats.route_ascent:
        class: WIO\EdkBundle\Statistics\RouteAscentHistogram
        arguments: ["@database_connection"]
        tags:
            - { name: cantiga.extension, point: edk.stats.route, module: edk }
    wio.edk.stats.route_files:
        class: WIO\EdkBundle\Statistics\RouteFilesChart
        arguments: ["@wio.edk.repo.route", "@translator"]
        tags:
            - { name: cantiga.extension, point: edk.stats.route, module: edk }
    wio.edk.stats.participant_number:
        class: WIO\EdkBundle\Statistics\ParticipantNumChart
        arguments: ["@database_connection", "@wio.edk.repo.participant", "@translator"]
        tags:
            - { name: cantiga.extension, point: edk.stats.participant, module: edk }
            - { name: cantiga.extension, point: edk.stats.area_participant, module: edk }
    wio.edk.stats.biggest_areas:
        class: WIO\EdkBundle\Statistics\BiggestAreasParticipantChart
        arguments: ["@wio.edk.repo.participant", "@translator"]
        tags:
            - { name: cantiga.extension, point: edk.stats.participant, module: edk }
    wio.edk.stats.participants_on_route:
        class: WIO\EdkBundle\Statistics\ParticipantsOnRouteChart
        arguments: ["@wio.edk.repo.participant", "@translator"]
        tags:
            - { name: cantiga.extension, point: edk.stats.area_participant, module: edk }
    wio.edk.stats.where_learnt:
        class: WIO\EdkBundle\Statistics\ParticipantWhereLearntChart
        arguments: ["@wio.edk.repo.participant", "@translator"]
        tags:
            - { name: cantiga.extension, point: edk.stats.participant, module: edk }
            - { name: cantiga.extension, point: edk.stats.area_participant, module: edk }