<?php
/*
 * This file is part of Cantiga Project. Copyright 2015 Tomasz Jedrzejewski.
 *
 * Cantiga Project is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * Cantiga Project is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Foobar; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 */
namespace Cantiga\CoreBundle\Form;

use Cantiga\CoreBundle\Api\ExtensionPoints\ExtensionPointFilter;
use Cantiga\CoreBundle\Api\ExtensionPoints\ExtensionPointsInterface;
use Cantiga\CoreBundle\Settings\ProjectSettings;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * Renders the form for editing the project settings. The form is autogenerated from the available
 * settings.
 *
 * @author Tomasz Jędrzejewski
 */
class ProjectSettingsForm extends AbstractType
{
	/**
	 * @var ProjectSettings
	 */
	private $settings;
	/**
	 * @var ExtensionPointsInterface 
	 */
	private $extensionPoints;
	/**
	 * @var ExtensionPointFilter
	 */
	private $filter;
	
	public function __construct(ProjectSettings $settings, ExtensionPointsInterface $extensionPoints, ExtensionPointFilter $filter)
	{
		$this->settings = $settings;
		$this->extensionPoints = $extensionPoints;
		$this->filter = $filter;
	}
	
	public function configureOptions(OptionsResolver $resolver)
    {
		$resolver->setDefaults(array(
			'translation_domain' => 'settings'
		));
    }

	public function buildForm(FormBuilderInterface $builder, array $options)
	{
		foreach ($this->settings as $setting) {
			$setting->createEditor($builder, $this->extensionPoints, $this->filter);
		}
		$builder->add('save', 'submit', array('label' => 'Save'));
	}

	public function getName()
	{
		return 'ProjectSettings';
	}
}
