<?php
namespace Cantiga\CoreBundle\Form;

use Cantiga\CoreBundle\Api\ExtensionPoints\ExtensionPointFilter;
use Cantiga\CoreBundle\Api\ExtensionPoints\ExtensionPointsInterface;
use Cantiga\CoreBundle\Settings\ProjectSettings;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * Renders the form for editing the project settings. The form is autogenerated from the available
 * settings.
 *
 * @author Tomasz Jędrzejewski
 */
class ProjectSettingsForm extends AbstractType
{
	/**
	 * @var ProjectSettings
	 */
	private $settings;
	/**
	 * @var ExtensionPointsInterface 
	 */
	private $extensionPoints;
	/**
	 * @var ExtensionPointFilter
	 */
	private $filter;
	
	public function __construct(ProjectSettings $settings, ExtensionPointsInterface $extensionPoints, ExtensionPointFilter $filter)
	{
		$this->settings = $settings;
		$this->extensionPoints = $extensionPoints;
		$this->filter = $filter;
	}
	
	public function configureOptions(OptionsResolver $resolver)
    {
		$resolver->setDefaults(array(
			'translation_domain' => 'settings'
		));
    }

	public function buildForm(FormBuilderInterface $builder, array $options)
	{
		foreach ($this->settings as $setting) {
			$setting->createEditor($builder, $this->extensionPoints, $this->filter);
		}
		$builder->add('save', 'submit', array('label' => 'Save'));
	}

	public function getName()
	{
		return 'ProjectSettings';
	}
}
